languageCode = "en"
languageName = "English"
weight = 2
title = "LebensInsider"

[params]
  displayName = "EN"
  isoCode = "en"
  logo = "logo.png"
  homepageImage = "img/lebeninsider-hero.webp"
  showLogo = true
  showName = true
  layout = "hero"
  showTitle = true
  rtl = false
  dateFormat = "January 2, 2006"
  description = "Real trips, real mistakes, real experiences."
  author.name = "LebensInsider"

[params.homepage]
  showRecent = true
  showRecentItems = 12
  showMoreLink = true
  showMoreLinkDest = "germany/travel"
  cardView = true
